---
- name: push /etc/nginx/nginx.conf
  template:
    src: "nginx.conf"
    dest: "/etc/nginx/nginx.conf"
    mode: 0644
    owner: root
    group: root
    setype: httpd_config_t
    seuser: system_u
  notify: restart nginx

- name: whitelist http/https firewalld services
  firewalld:
    service: "{{ item }}"
    immediate: yes
    permanent: true
    state: enabled
  loop:
    - http
    - https

- name: push dhparam file
  get_url:
    url: https://ssl-config.mozilla.org/ffdhe4096.txt
    dest: /etc/nginx/dhparam4096.txt
    mode: 0644
    owner: root
    group: root
    setype: httpd_config_t
    seuser: system_u
