---
- name: push default html pages
  copy:
    src: "files/html/{{ item }}"
    dest: "/var/www/html/{{ item }}"
    mode: 0644
    group: www-admin
    owner: www-admin
    setype: httpd_sys_content_t
  loop:
    - 404.html
    - 50x.html
    - index.html
    - nginx-logo.png
    - poweredby.png
