---
# https://mariadb.com/kb/en/library/upgrading-from-mariadb-55-to-mariadb-100/
# - mariadb101u-server
# - php72u-common
# - php72u-dba
# - php72u-fpm
# - php72u-gd
# - php72u-json
# - php72u-xml

- name: install/upgrade epel-release (CentOS only)
  when: ansible_distribution == 'CentOS'
  package:
    state: latest
    name: epel-release

- name: install/upgrade nginx
  package:
    state: latest
    name: nginx

- name: configure nginx
  template:
    src: "files/nginx.conf"
    dest: "/etc/nginx/nginx.conf"
    serole: object_r
    setype: httpd_config_t
    seuser: system_u
  notify: restart nginx

- name: add firewall rules for http/https
  firewalld:
    service: "{{ item }}"
    immediate: yes
    permanent: true
    state: enabled
  with_items:
    - http
    - https

- name: create group for web development permissions
  group: name=www-admin

- name: create system user for web development permissions
  user:
    comment: "system user for managing website deployments - do not use"
    create_home: no
    group: www-admin
    home: "/var/www"
    name: www-admin
    system: yes

- name: add target user to web development group
  user:
    append: yes
    groups: www-admin
    name: "{{ target_user }}"

- name: create root web directory (/var/www/)
  file:
    state: directory
    path: "/var/www/"
    mode: 0755
    setype: httpd_sys_content_t
    seuser: system_u

- name: create default server block root directory
  file:
    state: directory
    path: "/var/www/html/"
    mode: 0755
    group: www-admin
    owner: www-admin
    setype: httpd_sys_content_t
    seuser: system_u

- name: copy default html pages
  copy:
    src: "files/html/{{ item }}"
    dest: "/var/www/html/{{ item }}"
    mode: 0644
    group: www-admin
    owner: www-admin
    setype: httpd_sys_content_t
  with_items:
    - 404.html
    - 50x.html
    - index.html
    - nginx-logo.png
    - poweredby.png
