---
- name: create group for web development permissions
  group: name=www-admin

- name: create system user for web development permissions
  user:
    name: www-admin
    group: www-admin
    home: "/var/www"
    create_home: no
    comment: "system user for managing website deployments - do not use"
    system: yes

- name: add target user to www-admin group
  user:
    append: yes
    groups: www-admin
    name: "{{ target_user }}"

- name: create root web directory (/var/www/)
  file:
    state: directory
    path: "/var/www/"
    mode: 0755
    setype: httpd_sys_content_t
    seuser: system_u

- name: create default server block root directory
  file:
    state: directory
    path: "/var/www/html/"
    mode: 0755
    group: www-admin
    owner: www-admin
    setype: httpd_sys_content_t
    seuser: system_u
