---
- name: RedHat 7 - install PHP 7.3
  package:
    state: present
    name:
      - php73-bcmath
      - php73-common
      - php73-dba
      - php73-fpm
      - php73-gd
      - php73-json
      - php73-mbstring
      - php73-mysqlnd
      - php73-pecl-imagick
      - php73-xml
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "7"

- name: RedHat 8 - install PHP 7.2
  dnf:
    state: present
    name:
      - '@php:7.2'
      - php-bcmath
      - php-dba
      - php-gd
      - php-mysqlnd
      # - php-pecl-imagick
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "8"

- name: Fedora - install PHP 7.4
  dnf:
    state: present
    name:
      - php
      - php-bcmath
      - php-dba
      - php-gd
      - php-mysqlnd
      - php-pecl-imagick
  when:
    - ansible_facts['distribution'] == "Fedora"

- name: php - push php.ini
  copy:
    src: php.ini
    dest: "/etc/php.ini"
    mode: 0644
    seuser: system_u
  notify: restart php-fpm

- name: create php-fpm user
  user:
    name: php-fpm
    home: /var/lib/php/fpm
    shell: /sbin/nologin
    comment: "System user for php-fpm daemon - not for human use"
    system: yes

- name: php-fpm - push php-fpm.conf
  copy:
    src: php-fpm.conf
    dest: "/etc/php-fpm.conf"
    mode: 0644
    seuser: system_u
  notify: restart php-fpm

- name: php-fpm - push www.conf
  copy:
    src: www.conf
    dest: "/etc/php-fpm.d/www.conf"
    mode: 0644
    seuser: system_u
  notify: restart php-fpm

- name: nginx - push nginx-php-fpm.conf
  copy:
    src: nginx-php-fpm.conf
    dest: "/etc/nginx/conf.d/php-fpm.conf"
    mode: 0644
    seuser: system_u
  notify: restart nginx

- name: start/enable php-fpm service
  service:
    name: php-fpm
    state: started
    enabled: yes
