---
- name: install PHP 7.3
  package:
    state: present
    name:
      - php73-bcmath
      - php73-common
      - php73-dba
      - php73-fpm
      - php73-gd
      - php73-json
      - php73-mbstring
      - php73-mysqlnd
      - php73-pecl-imagick
      - php73-xml

- name: php - copy php.ini
  copy:
    src: php.ini
    dest: "/etc/php.ini"
    mode: 0644
    seuser: system_u

- name: php-fpm - copy php-fpm.conf
  copy:
    src: php-fpm.conf
    dest: "/etc/php-fpm.conf"
    mode: 0644
    seuser: system_u

- name: php-fpm - copy www.conf
  copy:
    src: www.conf
    dest: "/etc/php-fpm.d/www.conf"
    mode: 0644
    seuser: system_u
  notify: restart php-fpm

- name: nginx - copy nginx-php-fpm.conf
  copy:
    src: nginx-php-fpm.conf
    dest: "/etc/nginx/conf.d/php-fpm.conf"
    mode: 0644
    seuser: system_u
  notify: restart nginx

- name: start/enable php-fpm service
  service:
    name: php-fpm
    state: started
    enabled: yes
