---
# CAVEAT: This role requires LetsEncrypt SSL certs to already be in place.
# For future reference: https://certbot-dns-cloudflare.readthedocs.io/en/latest/

- name: push index.html and favicon.ico
  copy:
    src: "{{ item }}"
    dest: "/var/www/html/{{ item }}"
    mode: 0664
    group: www-admin
    owner: www-admin
    seuser: system_u
    setype: httpd_sys_content_t
  loop:
    - index.html
    - favicon.ico
