---
galaxy_info:
  role_name: wordpress
  author: Justin W. Flory
  description: Set up a WordPress site on a Fedora Server
  license: BSD-3-Clause

  min_ansible_version: 2.9

  platforms:
    - name: Fedora
      versions:
        - 32

  galaxy_tags:
    - linux
    - fedora
    - server
    - nginx

dependencies:
  - role: nginx
  - role: php-fpm
  - role: mariadb
