---
galaxy_info:
  role_name: firewalld
  author: Justin W. Flory
  description: Configure firewalld service on CentOS/RHEL Server
  license: BSD-3-Clause

  min_ansible_version: 2.9

  platforms:
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - linux
    - centos
    - rhel
    - server
    - firewalld
    - systemd

dependencies:
  - role: repos/epel
  - role: repos/ius
