---
# A quick and dirty playbook to provision a new Fedora laptop

- name: "Provision a new Fedora install with your preferred packages and other changes."
  hosts: localhost

  tasks:
    - name: "Update all existing packages."
      dnf: name=* state=latest

    - name: "Add RPMFusion repositories (Fedora 25)."
      dnf: name={{ item }} state=present
      with_items:
        - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-25.noarch.rpm
        - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-25.noarch.rpm

    - name: "Set up a Python 2/3 workspace."
      dnf: name={{ item }} state=present
      with_items:
        - python
        - python3
