---
- name: install/upgrade epel-release (CentOS only)
  when: ansible_distribution == 'CentOS'
  package:
    state: latest
    name: epel-release

- name: install/upgrade nginx
  package:
    state: latest
    name: nginx

- name: add firewall rule for http/https
  firewalld:
    immediate: yes
    permanent: yes
    service: "{{ item }}"
    state: enabled
  with_items:
    - http
    - https

- name: create root web directory (/var/www/)
  file:
    state: directory
    path: "/var/www/"
    mode: 0755
    seuser: system_u
    setype: httpd_sys_content_t

- name: create directory for SSL/TLS certificates
  file:
    state: directory
    path: "/etc/pki/tls/certs/private/"
    mode: 0750
    seuser: system_u
    setype: cert_t

- name: create group for web development permissions
  group: name=www-admin

- name: create system user for web development permissions
  user:
    create_home: no
    group: www-admin
    home: "/var/www/"
    name: www-admin
    system: yes

- name: add target user to web development group
  user:
    append: yes
    groups: www-admin
    name: "{{ target_user }}"
