---
# Installation for WordPress applications

- name: Install WordPress on a new host.
  hosts: wordpress

  tasks:
    - name: "Install WordPress PHP dependencies."
      yum: name={{ item }} state=present
      with_items:
      - MySQL-python
      - php
      - php-mysql
#      - httpd
#      - mariadb-server
      tags:
      - packages
      - wordpress

    - name: "Download WordPress from wordpress.com."
      get_url: >
        url=https://wordpress.org/wordpress-{{ wp_version }}.tar.gz
        dest=/srv/wordpress-{{ wp_version }}.tar.gz
        sha256sum="{{ wp_sha256sum }}"
      tags:
      - install
      - wordpress

    - name: "Extract WordPress to /opt/."
      command: >
        chdir=/opt/ tar xvf wordpress-{{ wp_version }}.tar.gz
        creates=/opt/wordpress-{{ inventory_hostname }}
      tags:
      - install
      - wordpress

    - name: "Add wordpress group."
      group: name=wordpress
      tags:
      - config
      - wordpress

    - name: "Add wordpress user."
      user: >
        name=wordpress
        group=wordpress
        home=/opt/wordpress-{{ inventory_hostname }}/
      tags:
      - config
      - wordpress

    - name: "Create WordPress MySQL database."
      mysql_db: name={{ wp_db_name }} state=present
      tags:
      - config
      - mysql
      - wordpress

    - name: "Create WordPress MySQL database user."
      mysql_user: >
        name={{ wp_db_user }}
        password={{ wp_db_password }}
        priv={{ wp_db_name }}.*:ALL
        host='localhost'
        state=present
      tags:
      - config
      - mysql
      - wordpress

    - name: "Copy WordPress config file to the server directory."
      template: >
        src=wp-config.php
        dest=/opt/wordpress-{{ inventory_hostname }}/
      notify:
      - restart apache
      tags:
      - config
      - wordpress

    - name: "Change ownership of WordPress installation."
      file: >
        path=/opt/wordpress-{{ inventory_hostname }}/
        owner=wordpress
        group=wordpress
        state=directory
        recurse=yes
      tags:
      - config
      - wordpress

    - name: "Install SELinux toolset for defining policy."
      yum: pkg=policycoreutils-python state=present
      tags:
      - selinux
      - wordpress

    - name: "Set SELinux policy for the WordPress directory."
      command: semanage fcontext -a -t httpd_sys_content_t "/opt/wordpress-{{ inventory_hostname }}(/.*)?"
      tags:
      - selinux
      - wordpress
      
    - name: "Set SELinux policy for wp-config.php."
      command: semanage fcontext -a -t httpd_sys_script_exec_t "/opt/wordpress-{{ inventory_hostname }}/wp-config\.php"
      tags:
      - selinux
      - wordpress

    - name: "Set SELinux policy for wp-content directory."
      command: semanage fcontext -a -t httpd_sys_rw_content_t "/opt/wordpress-{{ inventory_hostname }}/wp-content(/.*)?"
      tags:
      - selinux
      - wordpress

    - name: "Set SELinux policy for the *.php files."
      command: semanage fcontext -a -t httpd_sys_script_exec_t "/opt/wordpress-{{ inventory_hostname }}/.*\.php"
      tags:
      - selinux
      - wordpress

    - name: "Set SELinux policy for the Upgrade directory."
      command: semanage fcontext -a -t httpd_sys_rw_content_t "/opt/wordpress-{{ inventory_hostname }}/wp-content/upgrade(/.*)?"
      tags:
      - selinux
      - wordpress

    - name: "Set SELinux policy for the Uploads directory."
      command: semanage fcontext -a -t httpd_sys_rw_content_t "/opt/wordpress-{{ inventory_hostname }}/wp-content/uploads(/.*)?"
      tags:
      - selinux
      - wordpress

    - name: "Set SELinux policy for the wp-includes php files."
      command: semanage fcontext -a -t httpd_sys_script_exec_t "/opt/wordpress-{{ inventory_hostname }}/wp-includes/.*\.php"
      tags:
      - selinux
      - wordpress

    - name: "Restore SELinux context on all files."
      command: restorecon -Rv /opt/wordpress-{{ inventory_hostname }}
      tags:
      - selinux
      - wordpress
