---
- name: import Vault-encrypted variables
  include_vars: vault.yml

- name: "RedHat 7 - install mariadb-server v10.3 from IUS"
  package:
    state: present
    name:
      - mariadb103-server
      - python36-PyMySQL
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "7"

- name: "RedHat 8 - install mariadb-server AppStream"
  dnf:
    state: present
    name:
      - '@mariadb/server'
      - python3-PyMySQL
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "8"

- name: "Fedora - install mariadb-server"
  dnf:
    state: present
    name:
      - mariadb-server
      - python3-PyMySQL
  when: ansible_facts['distribution'] == "Fedora"

- name: push 999-custom.cnf to /etc/my.cnf.d/
  template:
    src: 999-custom.cnf
    dest: /etc/my.cnf.d/999-custom.cnf
    mode: 0644
    owner: root
    group: root
    setype: mysqld_etc_t
    seuser: system_u
  notify: restart mariadb.service

- name: start/enable mariadb.service
  service:
    name: mariadb.service
    state: started
    enabled: yes

- name: create/update root user permissions
  mysql_user:
    name: root
    host: localhost
    password: "{{ db.root_password }}"
    login_user: root
    login_host: localhost
    login_password: "{{ db.root_password }}"

- name: remove all anonymous user accounts
  mysql_user:
    name: ""
    host_all: yes
    state: absent
    login_user: root
    login_host: localhost
    login_password: "{{ db.root_password }}"
