---
- name: install IUS repositories
  package:
    state: present
    name: https://centos7.iuscommunity.org/ius-release.rpm

- name: install mariadb-server v10.3
  package:
    state: present
    name: mariadb103-server

- name: start/enable MariaDB
  service:
    name: mariadb
    state: started
    enabled: yes
