---
# requires --extra-vars="target='host1:host2:group etc' wp_domain='example.com:example.net'"

- name: Install a new WordPress instance
  hosts: "{{ target }}"
  remote_user: root

  roles:
    - apache
    - mariadb_server
    - wordpress
    - { role: wordpress, wp_domain: "{{ domains }}" }

  handlers:
  - include: "/home/jflory/Software/GSoC/ansible/handlers/restart_services.yml"
    static: yes
