---
# requires --extra-vars="target='host1:host2:group etc' wp_domain='example.com:example.net'"

- name: Install a new WordPress instance
  hosts: "{{ target }}"
  remote_user: root

  roles:
    - apache
    - mariadb_server
    - { role: wp_domain }

  handlers:
  - include: "{{ handlers }}/restart_services.yml"
