---
# requires --extra-vars="target='host1:host2:group etc'"

- name: Install a new WordPress instance
  hosts: "{{ target }}"
  remote_user: root

  roles:
    - apache
    - mariadb_server
    - wordpress

  handlers:
  - include: "{{ handlers }}/restart_services.yml"
