# requires --extra-vars="target='host1:host2:group etc'"

- name: Install a new WordPress instance in Fedora's infrastructure.
  hosts: "{{ target }}"
  remote_user: root
  roles:
    - apache
    - mariadb
    - wordpress
