---
# requires --extra-vars="target='host1:host2:group etc'"

- name: Install a new WordPress instance
  hosts: "{{ target }}"
  user: root

  roles:
    - apache
    - mariadb_server
    - wordpress
