---
- name: install SELinux policies
  package:
    state: present
    name:
      - selinux-policy
      - selinux-policy-targeted
      - container-selinux

- name: RedHat 8 - install fail2ban-selinux
  package:
    state: present
    name: fail2ban-selinux
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "8"

- name: install/upgrade setools
  package:
    state: latest
    name: setools

- name: set SELinux to enforcing
  selinux:
    policy: targeted
    state: enforcing
