---
- name: install git
  package:
    state: present
    name: git

- name: create root directory for Teleirc bots
  file:
    state: directory
    path: "/usr/lib64/teleirc"
    mode: 0755
    seuser: system_u

- name: git clone/pull RITlug/teleirc v1.2
  git:
    repo: "https://github.com/RITlug/teleirc.git"
    dest: "/usr/lib64/teleirc/{{ item.cn }}"
    version: v1.2
  with_items:
    - "{{ bots.fedora }}"
    - "{{ bots.fedora_ask }}"
    - "{{ bots.fedora_commops }}"
    - "{{ bots.fedora_diversity }}"
    - "{{ bots.fedora_docs }}"
    - "{{ bots.fedora_ec }}"
    - "{{ bots.fedora_flock }}"
    - "{{ bots.fedora_join }}"
    - "{{ bots.fedora_latam }}"
    - "{{ bots.fedora_mindshare }}"
    - "{{ bots.fedora_marketing }}"
    # - "{{ bots.fedora_pa }}"
    - "{{ bots.fedora_sq }}"
    - "{{ bots.fedora_summer_coding }}"
    - "{{ bots.fedora_women }}"
    - "{{ bots.fedora_zh }}"

# Too complex for now because of bad upstream packaging. Will revisit.
#
# - name: install yarn
# - name: yarn install

- name: add templated configuration
  template:
    src: env
    dest: "/usr/lib64/teleirc/{{ item.cn }}/.env"
    mode: 0640
    seuser: system_u
  with_items:
    - "{{ bots.fedora }}"
    - "{{ bots.fedora_ask }}"
    - "{{ bots.fedora_commops }}"
    - "{{ bots.fedora_diversity }}"
    - "{{ bots.fedora_docs }}"
    - "{{ bots.fedora_ec }}"
    - "{{ bots.fedora_flock }}"
    - "{{ bots.fedora_join }}"
    - "{{ bots.fedora_latam }}"
    - "{{ bots.fedora_mindshare }}"
    - "{{ bots.fedora_marketing }}"
    # - "{{ bots.fedora_pa }}"
    - "{{ bots.fedora_sq }}"
    - "{{ bots.fedora_summer_coding }}"
    - "{{ bots.fedora_women }}"
    - "{{ bots.fedora_zh }}"

- name: add templated systemd unit file
  template:
    src: teleirc.service
    dest: "/usr/lib/systemd/system/teleirc-{{ item.cn }}.service"
    mode: 0644
    seuser: system_u
    setype: systemd_unit_file_t
  with_items:
    - "{{ bots.fedora }}"
    - "{{ bots.fedora_ask }}"
    - "{{ bots.fedora_commops }}"
    - "{{ bots.fedora_diversity }}"
    - "{{ bots.fedora_docs }}"
    - "{{ bots.fedora_ec }}"
    - "{{ bots.fedora_flock }}"
    - "{{ bots.fedora_join }}"
    - "{{ bots.fedora_latam }}"
    - "{{ bots.fedora_mindshare }}"
    - "{{ bots.fedora_marketing }}"
    # - "{{ bots.fedora_pa }}"
    - "{{ bots.fedora_sq }}"
    - "{{ bots.fedora_summer_coding }}"
    - "{{ bots.fedora_women }}"
    - "{{ bots.fedora_zh }}"

- name: start/enable each Teleirc systemd unit file
  service:
    name: teleirc-{{ item.cn }}
    state: started
    enabled: yes
  with_items:
    - "{{ bots.fedora }}"
    - "{{ bots.fedora_ask }}"
    - "{{ bots.fedora_commops }}"
    - "{{ bots.fedora_diversity }}"
    - "{{ bots.fedora_docs }}"
    - "{{ bots.fedora_ec }}"
    - "{{ bots.fedora_flock }}"
    - "{{ bots.fedora_join }}"
    - "{{ bots.fedora_latam }}"
    - "{{ bots.fedora_mindshare }}"
    - "{{ bots.fedora_marketing }}"
    # - "{{ bots.fedora_pa }}"
    - "{{ bots.fedora_sq }}"
    - "{{ bots.fedora_summer_coding }}"
    - "{{ bots.fedora_women }}"
    - "{{ bots.fedora_zh }}"
