---
# Installation for WordPress applications

- name: "Install WordPress PHP dependencies."
  yum: name={{ item }} state=present
  with_items:
  - MySQL-python
  - php
  - php-mysql
  tags:
  - packages
  - wordpress

- name: "Install SELinux toolset for defining policy."
  yum: pkg=policycoreutils-python state=present
  tags:
  - selinux
  - wordpress

- name: "Add wordpress group."
  group: name=wordpress
  tags:
  - config
  - wordpress

- name: "Add wordpress user."
  user: >
    name=wordpress
    group=wordpress
    home=/opt/wordpress-{{ inventory_hostname }}
  tags:
  - config
  - wordpress

- name: "Create folders for installation."
  file:
    path=/opt/wordpress-{{ inventory_hostname }}
    state=directory
    group=wordpress
    recurse=true

- name: "Download and extract WordPress to /opt/."
  unarchive:
    src=https://wordpress.org/wordpress-{{ wp_version }}.tar.gz
    dest=/opt/wordpress-{{ inventory_hostname }}
    copy=no
    creates=/opt/wordpress-{{ inventory_hostname }}/wordpress
    group=wordpress
    owner=wordpress
  tags:
  - install
  - wordpress

- name: "Copy WordPress config file to the server directory."
  template: >
    src=wp-config.php
    dest=/opt/wordpress-{{ inventory_hostname }}/wordpress/
  notify:
  - restart apache
  tags:
  - config
  - wordpress

- name: "Change ownership of WordPress installation."
  file: >
    path=/opt/wordpress-{{ inventory_hostname }}/wordpress/
    owner=wordpress
    group=wordpress
    state=directory
    recurse=yes
  tags:
  - config
  - wordpress

- name: "Set SELinux policy for the WordPress directory."
  command: semanage fcontext -a -t httpd_sys_content_t "/opt/wordpress-{{ inventory_hostname }}/wordpress(/.*)?"
  tags:
  - selinux
  - wordpress
  
- name: "Set SELinux policy for wp-config.php."
  command: semanage fcontext -a -t httpd_sys_script_exec_t "/opt/wordpress-{{ inventory_hostname }}/wordpress/wp-config\.php"
  tags:
  - selinux
  - wordpress

- name: "Set SELinux policy for wp-content directory."
  command: semanage fcontext -a -t httpd_sys_rw_content_t "/opt/wordpress-{{ inventory_hostname }}/wordpress/wp-content(/.*)?"
  tags:
  - selinux
  - wordpress

- name: "Set SELinux policy for the *.php files."
  command: semanage fcontext -a -t httpd_sys_script_exec_t "/opt/wordpress-{{ inventory_hostname }}/wordpress/.*\.php"
  tags:
  - selinux
  - wordpress

- name: "Set SELinux policy for the Upgrade directory."
  command: semanage fcontext -a -t httpd_sys_rw_content_t "/opt/wordpress-{{ inventory_hostname }}/wordpress/wp-content/upgrade(/.*)?"
  tags:
  - selinux
  - wordpress

- name: "Set SELinux policy for the Uploads directory."
  command: semanage fcontext -a -t httpd_sys_rw_content_t "/opt/wordpress-{{ inventory_hostname }}/wordpress/wp-content/uploads(/.*)?"
  tags:
  - selinux
  - wordpress

- name: "Set SELinux policy for the wp-includes php files."
  command: semanage fcontext -a -t httpd_sys_script_exec_t "/opt/wordpress-{{ inventory_hostname }}/wordpress/wp-includes/.*\.php"
  tags:
  - selinux
  - wordpress

- name: "Restore SELinux context on all files."
  command: restorecon -Rv /opt/wordpress-{{ inventory_hostname }}/wordpress
  tags:
  - selinux
  - wordpress
