---
- name: create system user for limnoria bots
  user:
    name: limnoria
    comment: "system user to run limnoria IRC bots - do not use"
    system: yes
    home: "/usr/lib64/limnoria"
    create_home: no

- name: add target user to limnoria admin group
  user:
    name: "{{ target_user }}"
    groups: limnoria
    append: yes

- name: limnoria - create root directory for limnoria bots
  file:
    state: directory
    path: "/usr/lib64/limnoria"
    mode: 0755
    owner: limnoria
    group: limnoria
    seuser: system_u

- name: limnoria - create directory for each bot
  file:
    state: directory
    path: "/usr/lib64/limnoria/{{ item.cn }}"
    mode: 0755
    owner: limnoria
    group: limnoria
    seuser: system_u
  loop:
    - "{{ bots.fanshawe }}"

- name: install/upgrade limnoria
  package:
    state: latest
    name: limnoria

- name: "set file permissions to limnoria:limnoria in /usr/lib64/limnoria/"
  file:
    state: directory
    recurse: yes
    path: "/usr/lib64/limnoria"
    owner: limnoria
    group: limnoria

- name: copy limnoria configs
  template:
    src: "limnoria-{{ item.cn }}.conf"
    dest: "/usr/lib64/limnoria/{{ item.cn }}/limnoria-{{ item.cn }}.conf.ansible"
    mode: 0640
    owner: limnoria
    group: limnoria
    seuser: system_u
  loop:
    - "{{ bots.fanshawe }}"
  notify:
    - stop limnoria-fanshawe
    - move limnoria-fanshawe config
    - start/enable limnoria-fanshawe

- name: copy systemd service files
  template:
    src: "limnoria-{{ item.cn }}.service"
    dest: "/usr/lib/systemd/system/limnoria-{{ item.cn }}.service"
    mode: 0644
    seuser: system_u
    setype: systemd_unit_file_t
  loop:
    - "{{ bots.fanshawe }}"
