---
- name: add IUS repository 
  package:
    state: latest
    name: https://centos7.iuscommunity.org/ius-release.rpm

- name: install Python 3.6 from IUS
  # python36u-lxml: needed for DuckDuckGo plugin
  package:
    state: latest
    name:
      - python36u
      - python36u-pip
      - python36u-lxml

- name: create group for IRC bot admins
  group:
    name: irc-bot-admins

- name: create system user for IRC bots
  user:
    name: irc-bot-admins
    group: irc-bot-admins
    comment: System user for managing IRC bots - do not use
    create_home: no
    home: /opt/irc-bots
    system: yes

- name: add target user to IRC bot admins group
  user: name={{ target_user }} groups=irc-bot-admins append=yes

- name: create directory for IRC bots
  file:
    state: directory
    path: /opt/irc-bots
    owner: irc-bot-admins
    group: irc-bot-admins
    mode: 0775
    recurse: yes

- name: create directory for each bot
  file: state=directory path=/opt/irc-bots/{{ item }} owner=irc-bot-admins group=irc-bot-admins mode=0775 recurse=yes
  with_items:
    - limnoria-fanshawe

- name: install limnoria
  pip:
    executable: pip3.6
    state: latest
    name: limnoria

# Need to figure out how to use Ansible secrets first before this is possible
# - name: copy limnoria config (Fanshawe)
#   template:
#     src: limnoria-fanshawe.conf
#     dest: /opt/irc-bots/limnoria-fanshawe/limnoria-fanshawe.conf
