---
- name: nginx - create server block root directory
  file:
    state: directory
    path: "/var/www/{{ site_fqdn }}/"
    mode: 0755
    seuser: system_u
    setype: httpd_sys_content_t

- name: nginx - create server block html directory
  file:
    state: directory
    path: "/var/www/{{ site_fqdn }}/html/"
    mode: 0775
    group: www-admin
    owner: www-admin
    seuser: system_u
    setype: httpd_sys_content_t

- name: nginx - create server block logs directory
  file:
    state: directory
    path: "/var/www/{{ site_fqdn }}/logs/"
    mode: 0755
    group: nginx
    owner: nginx
    seuser: system_u
    setype: httpd_log_t

- name: nginx - push xenforo.conf
  # CAVEAT: This task requires LetsEncrypt SSL certs to already be in place.
  #         For future reference:
  #         https://certbot-dns-cloudflare.readthedocs.io/en/latest/
  template:
    src: xenforo.conf
    dest: "/etc/nginx/conf.d/xenforo.conf"
    mode: 0644
    owner: root
    group: root
    setype: httpd_config_t
    seuser: system_u
  notify:
    - restart php-fpm
    - restart nginx
