---
- name: selinux - set httpd_can_network_connect to persistently true
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: permissions - set php-fpm as owner of internal_data/sitemaps directory
  file:
    state: directory
    path: "/var/www/{{ site_fqdn }}/html/internal_data/sitemaps/"
    mode: 0775
    owner: php-fpm
    group: www-admin
    seuser: system_u
    setype: httpd_sys_rw_content_t

# TODO
# Not working yet. Not sure why. Ansible complains about the syntax of the
# `command` line. It is something about a variable, but not sure what is
# causing this yet. Leaving it here for posterity because eventually it needs
# to be fixed...
# === #
# - name: permissions - set 0777 on specific recommended subdirectories
#   command: "find /var/www/{{ site_fqdn }}/html/{{ item }} -type d -exec chmod 777 {} \;"
#   loop:
#     - data
#     - internal_data
