---
- name: add/upgrade EPEL repository
  package:
    state: latest
    name: epel-release

- name: enable CentOS PowerTools repository (for certbot)
  lineinfile:
    path: /etc/yum.repos.d/CentOS-PowerTools.repo
    regexp: '^enabled='
    line: "enabled=1"
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "8"

- name: install base EPEL packages
  package:
    state: present
    name:
      - certbot
