---
- name: install epel-release
  package:
    state: present
    name: epel-release

- name: create root directory for IRC bots
  file:
    state: directory
    path: "/usr/lib64/limnoria"
    mode: 0755
    seuser: system_u

- name: create directory for each bot
  file:
    state: directory
    path: "/usr/lib64/limnoria/{{ item }}"
    mode: 0755
    seuser: system_u
  with_items:
    - limnoria-fanshawe

- name: install/upgrade limnoria
  package:
    state: latest
    name: limnoria

- name: copy limnoria configs
  template:
    src: "{{ item }}.conf"
    dest: "/usr/lib64/limnoria/{{ item }}/{{ item }}.conf"
    mode: 0660
    seuser: system_u
  with_items:
    - limnoria-fanshawe

- name: copy systemd service files
  template:
    src: "{{ item }}.service"
    dest: "/usr/lib/systemd/system/{{ item }}.service"
    mode: 0664
    seuser: system_u
    setype: systemd_unit_file_t
  with_items:
    - limnoria-fanshawe

- name: restart/enable systemd services
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - limnoria-fanshawe
