---
- name: install ius-release
  package:
    state: present
    name: https://centos7.iuscommunity.org/ius-release.rpm

- name: install/upgrade python36u (from IUS)
  # python36u-lxml: needed for DuckDuckGo plugin
  package:
    state: latest
    name:
      - python36u
      - python36u-lxml
      - python36u-pip
      - python36u-setuptools

- name: create group for IRC bot administration
  group: name=irc-bot-admin

- name: create system user for IRC bot administration
  user:
    comment: "system user for managing IRC bots - do not use"
    create_home: no
    group: irc-bot-admin
    home: "/opt/irc-bots"
    name: irc-bot-admin
    system: yes

- name: add target user to IRC bot administration group
  user:
    append: yes
    groups: irc-bot-admin
    name: "{{ target_user }}"

- name: create root directory for IRC bots
  file:
    state: directory
    path: "/opt/irc-bots"
    mode: 0775
    group: irc-bot-admin
    owner: irc-bot-admin
    seuser: system_u

- name: create directory for each bot
  file:
    state: directory
    path: "/opt/irc-bots/{{ item }}"
    mode: 0775
    group: irc-bot-admin
    owner: irc-bot-admin
    seuser: system_u
  with_items:
    - limnoria-fanshawe

- name: install limnoria and other dependencies
  become_user: "{{ target_user }}"
  pip:
    executable: pip3.6
    state: latest
    extra_args: "--user"
    name:
      - beautifulsoup4
      - httpserver
      - limnoria
      - request
      - simplejson

- name: copy limnoria config (Fanshawe)
  template:
    src: "limnoria-fanshawe.conf"
    dest: "/opt/irc-bots/limnoria-fanshawe/limnoria-fanshawe.conf"
    mode: 0664
    group: irc-bot-admin
    owner: irc-bot-admin
    seuser: system_u
