---
- name: synchronize estrella
  hosts: estrella
  become: yes

  roles:
    - role: common-centos/7
      git_conf_dir: /home/jflory/git/conf
      target_user: jflory
      user_home_dir: /home/jflory
