---
- import_playbook: bryn.yml
- import_playbook: cortana.yml
- import_playbook: derezzed.yml
- import_playbook: estrella.yml
- import_playbook: fiction.yml
- import_playbook: horizon.yml
- import_playbook: telegram-irc.yml
