---
- name: bryn - back up and export all InfluxDB databases
  hosts: bryn
  become: yes

  vars:
    target_user: jflory
    user_home_dir: "/home/jflory"

  tasks:
    - name: export databases with influxdb tools
      command: "influxd backup -portable /tmp/influxdb-backup/"
      args:
        creates: /tmp/influxdb-backup/

    - name: create local backup - compress all database dumps together
      archive:
        path: /tmp/influxdb-backup/
        dest: "{{ user_home_dir }}/wkspc/influxdb-backup-{{ ansible_date_time.iso8601 }}.gz"
        remove: yes
        mode: 0644
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        seuser: system_u

    - name: clean up - delete /tmp/influxdb-backup/
      file:
        state: absent
        path: /tmp/influxdb-backup/
