---
- name: export all data for a single WordPress installation
  hosts: horizon.jwf.io
  become: yes

  vars:
    mysql_db_name: wp_blog_justinwflory_com
    mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35383232646137623633613834616237636537353930326232346632376138373131623935613931
          6566636636383361323132646335623162663438323265340a643966333439343436333332386336
          61343363363133346666306330366335376463363865643234633034623861653565303231373264
          3136653739316665350a643631656330623937393537326362376132373762663234383233353736
          39326431386564356261643438623264356131313534663931393934616264646164643037656132
          6235326261346535386366643133356430653435383639616535
    mysql_user: wordpress
    site_dir: "/var/www/{{ site_fqdn }}"
    site_fqdn: blog.jwf.io
    target_group: jflory
    target_user: jflory
    user_home_dir: "/home/jflory"

  tasks:
    - name: install required libraries
      package:
        state: present
        name:
          - python2-PyMySQL
          - python-backports-lzma

    - name: export and compress MySQL database, save to target user home directory
      mysql_db:
        name: "{{ mysql_db_name }}"
        state: dump
        target: "/tmp/{{ site_fqdn }}-db.sql"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"

    - name: compress dumped database archive
      archive:
        path: "/tmp/{{ site_fqdn }}-db.sql"
        dest: "/tmp/{{ site_fqdn }}-db.sql.xz"
        format: xz
        remove: yes

    - name: (hack) create file for archive to write to successfully
      file:
        path: "/tmp/{{ site_fqdn }}-www-content.tar.xz"
        state: touch

    - name: archive existing site content, save to target user home directory
      archive:
        path: "{{ site_dir }}"
        dest: "/tmp/{{ site_fqdn }}-www-content.tar.xz"
        format: xz

    - name: zip everything together for convenience
      archive:
        path:
          - "/tmp/{{ site_fqdn }}-www-content.tar.xz"
          - "/tmp/{{ site_fqdn }}-db.sql.xz"
        dest: "{{ user_home_dir }}/{{ site_fqdn }}.zip"
        format: zip
        remove: yes
        owner: "{{ target_user }}"
        group: "{{ target_group }}"
        seuser: system_u
