---
- hosts: ccmc-game
  remote_user: minecraft

  vars:
    server_names: "{{ servers }}"
  
  vars_files:
    - vars.yml

  tasks:
    - name: "Install dependencies of PaperSpigot (i.e. Java)."
      yum: name=java-1.8.0-openjdk state=present
      become: yes

    - name: "Create new server directories."
      file: path=/home/{{ remote_user }}/servers/{{ item }} state=directory
      with_items: "{{ server_names }}"

    - name: "Ensure the GLOBAL directory exists."
      file: path=/home/{{ remote_user }}/servers/GLOBAL state=directory

    - name: "Ensure there is a JAR of the latest build of PaperSpigot."
      get_url:
        dest: /home/{{ remote_user }}/servers/GLOBAL/paperspigot.jar
        url: https://ci.destroystokyo.com/job/PaperSpigot/lastSuccessfulBuild/artifact/paperclip.jar

    - name: "Create symbolic links for the PaperSpigot server JAR."
      file: src=/home/{{ remote_user }}/servers/GLOBAL/paperspigot.jar dest=/home/{{ remote_user }}/servers/{{ item }}/{{ item }}-spigot.jar state=link
      with_items: "{{ server_names }}"

    - name: "Create tmux sessions for new servers."
      command: tmux new -d -s {{ item }}
      with_items: "{{ server_names }}"

    - name: "Create a start.sh script for new servers."
      lineinfile:
        create: yes
        dest: /home/{{ remote_user }}/servers/{{ item }}/start.sh
        line: java -Xms256M -Xmx256M -Dcom.mojang.eula.agree=true -jar {{ item }}-spigot.jar
        mode: u+x
        state: present
      with_items: "{{ server_names }}"

    - name: "Start the new servers."
      shell: >
        tmux send-keys -t {{ item }} "cd ~/servers/{{ item }} && ./start.sh" Enter
      with_items: "{{ server_names }}"