---
- hosts: ccmc-game
  remote_user: minecraft

  vars:
    server_names: "{{ servers }}"
  
  vars_files:
    - vars.yml

  tasks:
    - name: "Shut down the servers being removed."
      shell: >
        tmux send-keys -t {{ item }} "stop" Enter
      with_items: "{{ server_names }}"

    - name: "Create tar archive and place into backups dir."
      command: tar -zcvf /home/{{ remote_user}}/backups/old-servers/{{ item }}.tar.gz /home/{{ remote_user }}/servers/{{ item }}
      with_items: "{{ server_names }}"

    - name: ""