---
- hosts: ccmc-game
  remote_user: minecraft

  vars_files:
    - vars.yml

  tasks:
    - name: "Install tmux." 
      become: yes
      yum: name=tmux state=present

    - name: "Create tmux sessions for each server."
      command: tmux new -d -s {{ item }}
      with_items: "{{ game_tmux_sessions }}"

    - name: "Create servers/ directory in home folder."
      file: path=/home/{{ remote_user }}/servers state=directory

    - name: "Start each server in its tmux session."
      shell: >
        tmux send-keys -t {{ item }} "cd ~/servers/{{ item }} && ./start.sh" Enter
      with_items: "{{ game_tmux_sessions }}"