---
- name: ensure target user ({{ target_user }}) exists
  user:
    name: "{{ target_user }}"

- name: create SSH config directories for target user (~/.ssh)
  file:
    state: directory
    path: "{{ user_home_dir }}/.ssh"
    mode: 0700
    owner: "{{ target_user }}"
    group: "{{ target_group }}"
    setype: ssh_home_t
    seuser: system_u

- name: add SSH public key to authorized_keys for target user (~/.ssh/authorized_keys)
  template:
    src: authorized_keys
    dest: "{{ user_home_dir }}/.ssh/authorized_keys"
    mode: 0400
    owner: "{{ target_user }}"
    group: "{{ target_group }}"
    setype: ssh_home_t
    seuser: system_u

- name: push /etc/ssh/sshd_config
  template:
    src: sshd_config
    dest: "/etc/ssh/sshd_config"
    mode: 0600
    setype: etc_t
    seuser: system_u
  notify: restart sshd
