---
- name: synchronize jflory7.fedoraproject.org
  hosts: fedorapeople.org

  vars:
    target_group: jflory7
    target_user: jflory7
    target_user_name: Justin W. Flory
    user_home_dir: /home/fedora/jflory7

  roles:
    - { role: sites/jflory7.fedorapeople.org, tags: ['fedorapeople', 'sites'] }
