---
- name: synchronize lorge
  hosts: lorge.jwf.io
  become: yes

  vars:
    target_group: jwf
    target_user: jwf
    target_user_name: Justin W. Flory
    user_home_dir: /home/jwf

  roles:
    - { role: system/selinux, tags: ['selinux', 'system'] }
    - { role: firewalld, tags: ['firewalld', 'system'] }
    - { role: mariadb, tags: mariadb }
    - { role: php-fpm, tags: php-fpm }
    - { role: sshd, tags: ['sshd', 'system'] }
    - { role: sites/lorge.jwf.io, tags: ['lorge', 'sites'] }
    - role: wordpress
      vars:
        site_fqdn: blog.jwf.io
      tags:
        - 'blog'
        - 'sites'
