---
- name: synchronize midnight
  hosts: midnight.jwf.io
  become: yes

  vars:
    target_group: jwf
    target_user: jwf
    target_user_name: "Justin W. Flory (he/him)"
    user_home_dir: /home/jwf

  roles:
    - { role: system/selinux, tags: ['selinux', 'system'] }
    - { role: firewalld, tags: ['firewalld', 'system'] }
    - { role: sshd, tags: ['sshd', 'system'] }
    - { role: sites/midnight.jwf.io, tags: ['horizon', 'sites'] }
    - { role: sites/i.jwf.io, tags: ['screenshot', 'sites'] }
    - { role: sites/mirror.jwf.io, tags: ['mirror', 'sites'] }
